package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.ObjectLink;

import greendao.ObjectLinkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig objectLinkDaoConfig;

    private final ObjectLinkDao objectLinkDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        objectLinkDaoConfig = daoConfigMap.get(ObjectLinkDao.class).clone();
        objectLinkDaoConfig.initIdentityScope(type);

        objectLinkDao = new ObjectLinkDao(objectLinkDaoConfig, this);

        registerDao(ObjectLink.class, objectLinkDao);
    }
    
    public void clear() {
        objectLinkDaoConfig.getIdentityScope().clear();
    }

    public ObjectLinkDao getObjectLinkDao() {
        return objectLinkDao;
    }

}
